# Generated by Django 4.0.6 on 2022-08-25 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AuthuserApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="firstname",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
