# Generated by Django 4.0.6 on 2022-08-25 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AuthuserApp", "0002_alter_user_firstname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_no",
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
