# Generated by Django 4.0.6 on 2022-07-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0002_alter_reservation_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passenger',
            old_name='lastNmae',
            new_name='lastName',
        ),
    ]
