# Generated by Django 4.0.6 on 2022-07-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0004_remove_passenger_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='departureCity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
